consignaciones/urls.py
from django.conf.urls import include, url
from .views import *

urlpatterns = [
    url(r'^consignaciones/agregar$', agregarconsignacion, name='consignaciones_agregar'),
    url(r'^consignaciones/listar$', listarconsignaciones, name='consignaciones_listar'),
    url(r'^consignaciones/reportes$', listarconsignacionestodas, name='consignaciones_listar_todas'),
    url(r'^consignaciones/agregar-ajax$', agregarconsignacion2, name='consignaciones_agregar'),
    url(r'^consignaciones/editar/(?P<pk>[0-9]+)/$', editarconsignaciones, name='consignaciones_editar_datos'),
    url(r'^consignaciones/editar/(?P<pk>[0-9]+)/observacion$', editarconsignacionesobservacion, name='consignaciones_editar_observacion'),
    url(r'^consignaciones/editar/(?P<pk>[0-9]+)/pagado$', editarconsignacionespagado, name='consignaciones_editar_pagado'),
    url(r'^consignaciones/editar/(?P<pk>[0-9]+)/devuelto$', editarconsignacionesdevuelto, name='consignaciones_editar_devuelto'),
    url(r'^consignaciones/editar/(?P<pk>[0-9]+)/pagoydevolvio$', editarconsignacionespagoydevolvio, name='consignaciones_editar_pagoydevolvio'),
    url(r'^consignaciones/eliminar/(?P<pk>[0-9]+)/$', eliminarconsignacion, name='consignaciones_eliminar'),
    ]

inicio/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout_then_login
from django.views.generic  import TemplateView
from . import views
from .views import *
urlpatterns = [
    url(r'^$', login, {'template_name': 'inicio/index.html'}, name='home'),
    url(r'^salir/$', logout_then_login, name='salir'),
    url(r'^comisiones/agregar$', agregarcomision, name='agregarcomision'),
    url(r'^comisiones/listar$', listarcomisiones, name='comisiones_listar'),
    url(r'^comisiones/ranking$', rankingcomisiones, name='ranking_listar'),
    #url(r'^comisiones/buscar-ajax$', buscarventas, name='ventas_buscar_ajax'),
    url(r'^comisiones/editar/(?P<pk>[0-9]+)/$', editarcomision, name='comisiones_editar'),
    url(r'^comisiones/eliminar/(?P<pk>[0-9]+)/$', eliminarcomision, name='comisiones_eliminar'),
    url(r'^caja/listar$', listarcajas, name='caja_listar'),
    url(r'^comisiones/reportes$', reportecomisiones, name='reporte_comisiones'),
    url(r'^comisiones/reportepersona$', reportecomsionpersona, name='reportecomisionpersona'),
    url(r'^caja/abrir$', abrircaja, name='caja_abrir'),
    url(r'^caja/cerrar$', cerrarcaja, name='caja_cerrar'),
    url(r'^caja/resumen/(?P<pk>[0-9]+)/$', resumencaja, name='resumen_caja'),
    url(r'^usuario/agregar$', agregarusuario, name='usuario_agregar'),
    ]

modasmartphonesac/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('inicio.urls')),
    url(r'', include('personas.urls')),
    url(r'', include('productos.urls')),
    url(r'', include('compras.urls')),
    url(r'', include('consignaciones.urls')),
    url(r'', include('ventas.urls')),
    url(r'', include('salidas.urls')),
    url(r'', include('desbloqueos.urls')),
]

consignaciones/models.py
from __future__ import unicode_literals
from django.db import models
from personas.models import Personas
from productos.models import Producto
import datetime
from django.utils import timezone
from django.db.models.signals import *
from django.dispatch import receiver
from django.shortcuts import get_object_or_404

# Create your models here.
class Consignacion(models.Model):
    personas = models.ForeignKey(Personas, on_delete=models.CASCADE)
    fecha = models.DateTimeField()
    pagado = models.BooleanField(default=False)
    devuelto = models.BooleanField(default=False)
    observacion = models.CharField(max_length=100, blank=True, null=True)
    productos = models.ManyToManyField(Producto, through='detalle_consignacion')
    def __str__(self):
        return self.personas.nombres + str(self.fecha)

class detalle_consignacion(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    consignacion = models.ForeignKey(Consignacion, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)

consignaciones/forms.py
from django.forms import *
from .models import *
import datetime

class ConsignacionForm(forms.Form):
    personas = CharField(widget=HiddenInput)

class Detalle_ConsignacionForm(forms.Form):
    producto = CharField(widget=HiddenInput)
    cantidad = IntegerField()

consignaciones/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
import datetime
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from personas.models import Personas
from productos.models import Producto
from .forms import *
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
import json

@login_required
def agregarconsignacion(request):
    return render(request, "consignaciones/agregar.html", {})

@login_required
def listarconsignaciones(request):
    lista = Consignacion.objects.filter(Q(pagado=False) | Q(devuelto=False)).order_by('-fecha')
    page = request.GET.get('page')
    paginator = Paginator(lista, 10)
    try:
        lista = paginator.page(page)
    except PageNotAnInteger:
        lista = paginator.page(1)
    except EmptyPage:
        lista = paginator.page(1)
    return render(request, 'consignaciones/listar.html', { 'lista': lista, 'paginator':paginator })

@login_required
def listarconsignacionestodas(request):
    lista = Consignacion.objects.all().order_by('-fecha')
    page = request.GET.get('page')
    paginator = Paginator(lista, 10)
    try:
        lista = paginator.page(page)
    except PageNotAnInteger:
        lista = paginator.page(1)
    except EmptyPage:
        lista = paginator.page(1)
    return render(request, 'consignaciones/reportes.html', { 'lista': lista, 'paginator':paginator })

@login_required
def agregarconsignacion2(request):
    if request.method == "GET":
        try:
            c = Consignacion()
            clien = int(request.GET['cliente'])
            obse = str(request.GET['observacion']).lower()
            fecha = datetime.datetime.now()
            c.personas = get_object_or_404(Personas, pk=clien)
            c.fecha = fecha
            c.devuelto = False
            c.pagado = False
            c.observacion = obse.lower()
            c.save()
            productos = request.GET.getlist('datos[]')
            for prod in productos:
                p = prod.split(",")
                dc = detalle_consignacion()
                itempro = get_object_or_404(Producto, pk=p[0])
                dc.producto = itempro
                dc.consignacion = c
                dc.cantidad = p[1]
                dc.save()
                detalle = "ok"
        except Exception as e:
            detalle = "Error: " + str(e)
            print(detalle)
        finally:
			return HttpResponse(
				json.dumps(detalle),
				content_type="application/json"
			)

@login_required
def buscarconsignaciones(request):
    if request.is_ajax():
        texto = request.GET['term'].lower()
        if texto is not None:
            clase = Consignacion.objects.filter(Q(personas__nombres__contains = texto)).order_by(-fecha)
            lista = []
            for c in clase:
				lista.append({'pk':c.pk,'categoria':c.categoria.nombre, 'marca':c.modelo.marca.nombre ,'modelo':c.modelo.nombre,'barra':c.barra, 'mayor':str(c.precio.mayor), 'punto':str(c.precio.punto), 'cliente':str(c.precio.cliente), 'stock':c.stock})
            data = json.dumps(lista)
            return HttpResponse(data, content_type='application/json')


@login_required
def editarconsignaciones(request, pk):
    c = get_object_or_404(Consignacion, pk=pk)
    productos = list(detalle_consignacion.objects.filter(consignacion=pk))
    return render(request, "consignaciones/editar.html", {'c':c, 'productos':productos})

@login_required
def editarconsignacionesobservacion(request, pk):
    if request.method == "GET":
        try:
            c = Consignacion(pk=pk)
            obse = str(request.GET['observacion']).lower()
            c.observacion = obse.lower()
            c.save(update_fields=["observacion"])
            detalle="ok"
        except Exception as e:
            detalle = "Error: " + str(e)
        finally:
			return HttpResponse(
				json.dumps(detalle),
				content_type="application/json"
			)

@login_required
def editarconsignacionespagado(request, pk):
    if request.method == "GET":
        try:
            c = Consignacion(pk=pk)
            c.pagado=True
            c.save(update_fields=["pagado"])
            detalle="ok"
        except Exception as e:
            detalle = "Error: " + str(e)
        finally:
			return HttpResponse(
				json.dumps(detalle),
				content_type="application/json"
			)

@login_required
def editarconsignacionespagoydevolvio(request, pk):
    if request.method == "GET":
        try:
            c = Consignacion(pk=pk)
            c.pagado=True
            c.devuelto=True
            c.save(update_fields=["pagado","devuelto"])
            detalle="ok"
        except Exception as e:
            detalle = "Error: " + str(e)
        finally:
			return HttpResponse(
				json.dumps(detalle),
				content_type="application/json"
			)

@login_required
def editarconsignacionesdevuelto(request, pk):
    if request.method == "GET":
        try:
            c = Consignacion(pk=pk)
            c.devuelto=True
            c.save(update_fields=["devuelto"])
            detalle="ok"
        except Exception as e:
            detalle = "Error: " + str(e)
        finally:
			return HttpResponse(
				json.dumps(detalle),
				content_type="application/json"
			)

@login_required
def eliminarconsignacion(request, pk):
    c = get_object_or_404(Consignacion, pk=pk)
    productos = list(detalle_consignacion.objects.filter(consignacion=pk))
    detalle = 0
    if request.method == 'POST':
        try:
            c.delete()
            print("consignacion borrada")
            for p in productos:
                print("productos borrados")
                p.delete()
        except Exception, e:
            detalle = "Error: " + str(e)
        finally:
            if detalle != 0:
                print(detalle)
                return render(request, 'consignaciones/eliminar.html', {'c': c, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('consignaciones_listar'))
    else:
        return render(request, 'consignaciones/eliminar.html', {'c': c, 'productos':productos})

templates/consignaciones/agregar.html
{% extends 'inicio/base.html' %}
{% block contenido %}
<div class="off-canvas-content" data-off-canvas-content>
 <div class="row titulo large-8 large-offset-2 medium-8 medium-offset-2 small-12">
   <form id="form" class="" action="#" method="post">{% csrf_token %}
      <h3>Agregar Consignacion</h3>
        {% if detalle %}
          {% if detalle != "0" %}
          <h5 class="error">
            {{detalle}}
          </h5>
          {% endif %}
        {% endif %}
      <label for="id_personas">Seleccione Cliente: (Requerido)</label>
      <input id = "id_personas" type="hidden">
      <div class="input-group">
        <a href="#" class="botonopenmodal input-group-button" id="abrirmodal" data-open="exampleModal1"><i class="material-icons">search</i></a>
        <input type="text" class=" input-group-field" readonly id="id_cliente" name="" value="">
      </div>
      <label for="id_observacion">Observaciones: (Opcional)</label>
      <textarea id="id_observacion" name="id_observacion" rows="2" cols="40"></textarea>
      <div class="callout medium">
        <h4>Agregar Productos:</h4>
        <div class="input-group">
          <input id="id_producto" type="hidden" name="" value="">
          <a href="#" class="botonopenmodal input-group-button" id="abrirmodal2" data-open="exampleModal2"><i class="material-icons">search</i></a>
          <input type="text" class=" input-group-field" readonly placeholder="Seleccione un producto" id="producto" name="" value="">
        </div>
        <div class="row">
          <div class="columns small-3">
            <label for="cantidad">Cantidad</label>
            <input id="cantidad" type="number" name="" value="">
          </div>
          <div class="columns small-3">
          </div>
          <div class="columns small-3">
            <a href="#" onclick="agregarproducto();" class="button">Agregar producto</a>
          </div>
        </div>

 </div>
 <!--MODAL PARA CLIENTE-->
   <div class="reveal titulo" id="exampleModal1" data-reveal>
    <h3>Seleccionar Cliente</h3>
    <div class="input-group input-group-rounded columns large-6 medium-4">
      <span class="input-group-label"><i class="material-icons">search</i></span>
      <input type="text" id="buscadorcliente" name="buscador" class="buscador input-group-field" placeholder="Buscar cliente" id="buscador">
    </div>
      <table class="table-scroll" id="tablacliente">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Seleccionar</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    <button class="close-button" data-close aria-label="Close modal" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<!--MODAL PARA CLIENTE-->
<!--MODAL PARA PRODUCTO-->
  <div class="reveal titulo" id="exampleModal2" data-reveal>
   <h3>Seleccionar Producto</h3>
   <div class="input-group input-group-rounded columns large-6 medium-4">
     <span class="input-group-label"><i class="material-icons">search</i></span>
     <input type="text" id="buscadorproducto" name="buscador" class="buscador input-group-field" placeholder="Buscar producto">
   </div>
     <table class="table-scroll" id="tablaproducto">
       <thead>
         <tr>
           <th>Categoria</th>
           <th>Marca</th>
           <th>Modelo</th>
           <th>Seleccionar</th>
         </tr>
       </thead>
       <tbody>
       </tbody>
     </table>
   <button class="close-button" data-close aria-label="Close modal" type="button">
     <span aria-hidden="true">&times;</span>
   </button>
 </div>
<!--MODAL PARA PRODUCTO-->
</div>
{% endblock %}
{% block contenido_ancho %}
<div class="off-canvas-content" data-off-canvas-content>
 <div class="row titulo large-10 large-offset-1 medium-10 medium-offset-1 small-12">
<div class="callout medium">
  <h4>Productos de la Consignacion:</h4>
  <table id="listaproductos">
    <thead>
      <tr>
        <th width="5%">ID</th>
        <th width="">Producto</th>
        <th width="15%">Cantidad</th>
        <th width="5%">Eliminar</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<button id="guardar" type="button" class="button boton1" name="entrar" onclick="guardarconsignacion();">Guardar</button>
</div>
</form>
</div>
{% endblock %}
{%block script%}
$( document ).ready(function() {
  $("#abrirmodal").focus();
});
$('#cantidad').keypress(function(e) {
    if(e.which == 13 && $("#id_producto").val()!='') {
        agregarproducto();
    }
});
$('#buscadorcliente').change(function(){
  a = $("#buscadorcliente").val().length;
  if(a>2){
    $("#tablacliente tbody tr").remove();
    texto = $("#buscadorcliente").val();
    $.ajax({
      data: {'term':texto},
      url: "/personas/buscar-ajax",
      type: "get",
      success: function(data){
        for(var i = 0; i<data.length; i++){
          $nom = data[i].nombres;
          if(data.length==1){
            seleccionar(data[i].pk, $nom);
          }
          else{
          nuevafila="<tr>";
          nuevafila +="<td>" + $nom + "</td>" +
                      '<td><a href="#" onclick="seleccionar(' + data[i].pk + ",\'"+  $nom + '\')"><i class=material-icons>thumb_up</i></a></td></tr>';
          $("#tablacliente").append(nuevafila);
          }
       }
      }
    });
  }
});
$('#buscadorproducto').change(function(){
  a = $("#buscadorproducto").val().length;
  if(a>1){
    texto = $("#buscadorproducto").val();
    $("#tablaproducto tbody tr").remove();
    $.ajax({
      data: {'term':texto},
      url: "/productos/buscar-ajax2",
      type: "get",
      success: function(data){
        for(var i = 0; i<data.length; i++){
          categoria = data[i].categoria.replace(/\s+/g, '-');
          modelo = data[i].modelo.replace(/\s+/g, '-');
          marca = data[i].marca.replace(/\s+/g, '-');
          nombrecompleto = categoria + '-' + marca + '-' + modelo;
          if(data.length==1){
            seleccionar2(data[i].pk, nombrecompleto);
          }
          else{
          nuevafila="<tr>";
          nuevafila +="<td>" + data[i].categoria + "</td>" +
                      "<td>" + data[i].marca + "</td>" +
                      "<td>" + data[i].modelo + "</td>" +
                      "<td><a href=javascript:seleccionar2("+ data[i].pk + ",'" + nombrecompleto +"')><i class=material-icons>thumb_up</i></a></td></tr>";
          $("#tablaproducto").append(nuevafila);}
       }

      }
    });
  }
});
function seleccionar(id, modelo){
  $("#id_personas").val(id);
  $("#id_cliente").val(modelo);
  $("#exampleModal1").foundation('close');
  $("#buscadorcliente").val('');
  $("#tablacliente tbody tr").remove();
  $("#id_observacion").focus();
}
function seleccionar2(id, modelo){
  $("#id_producto").val(id);
  $("#producto").val(modelo);
  $("#exampleModal2").foundation('close');
  $("#buscadorproducto").val('');
  $("#tablaproducto tbody tr").remove();
  $("#cantidad").focus();
}
function agregarproducto(){
  if(($("#cantidad").val()!='') && ($("#id_producto").val()!='')){
    fila =  '<tr><td id=\"colpk\" >'+ $("#id_producto").val()+'</td><td>'+
                        $("#producto").val()+'</td><td id=\"colcantidad\">' +
                        $("#cantidad").val()+'</td><td>' +
                        '<a href="#" onclick=\"eliminaritem(this);\"> <i class="material-icons">delete</i></a> </td></tr>';
    $("#listaproductos").append(fila);
    $("#id_producto").val('');
    $("#producto").val('');
    $("#cantidad").val('');
    $("#abrirmodal2").focus();
  }

}
function eliminaritem(arg){
  arg.closest("tr").remove();
  $("#abrirmodal2").focus();
}
$("#id_observacion").change(function(){
  var filas = []
  var fila = [];
  $("#listaproductos>tbody>tr").each(function(){
        a = $(this).find('td[id=\"colpk\"]').text();
        b = $(this).find('td[id=\"colcantidad\"]').text();
        fila.push({prod:a, cant:b });
        filas.push({'producto':fila});
    });
    $("#id_productos").val($.param({p: filas}));
});
$("#form").on('submit', function(evt){
    evt.preventDefault();
 });
function guardarconsignacion(){
    datos = new Array();
    $("#listaproductos>tbody>tr").each(function(){
          producto = $(this).find('td[id=\"colpk\"]').text();
          cantidad = $(this).find('td[id=\"colcantidad\"]').text();
          dato = new Array(producto, cantidad);
          datos.push(dato);
      });
      if($('#id_personas').val()!='' && !($.isEmptyObject(datos))){
      $.ajax({
        url: "agregar-ajax",
        dataType: "json",
        data: {'cliente':$('#id_personas').val(), 'observacion':$("#id_observacion").val() , 'datos[]':datos},
        success: function(detalle){
          if(detalle=="ok"){
            window.location.replace("/consignaciones/listar");
          }
          else{
            console.log("hay que implementar un div para mostrat error");
          }
        }
      });
	   }
}

{% endblock %}

templates/consignaciones/editar.html
{% extends 'inicio/base.html' %}
{% block contenido %}
<div class="off-canvas-content" data-off-canvas-content>
  <div class="callout clearfix">
    <div class="row">
      <div class="columns large-4">
        <a href="#" onclick="editarconsignacionespagado();" class="button">PAGO TODO</a>
      </div>
      <div class="columns large-4">
        <a href="#" onclick="pagoydevolvio();" class="button">PAGO Y DEVOLVIO</a>
      </div>
      <div class="columns large-4 medium-4 small-12">
        <a href="#" onclick="editarconsignacionesdevuelto();" class="button float-left">DEVOLVIO TODO</a>
      </div>
    </div>
  </div>
  <div class="row titulo large-8 large-offset-2 medium-8 medium-offset-2 small-12">
  {% csrf_token %}
  <h3>Detalles de la Consignacion</h3>
    {% if detalle %}
      {% if detalle != "0" %}
      <h5 class="error">
        {{detalle}}
      </h5>
      {% endif %}
    {% endif %}
    <div class="callout medium">
      <h4>Datos generales</h4>
      <table>
        <tbody>
          <tr>
            <td>Cliente</td>
            <td>{{c.personas.nombres|upper}}</td>
          </tr>
          <tr>
            <td>Fecha</td>
            <td>{{c.fecha|date:'d/m/Y H:m'}}</td>
          </tr>
          <tr>
            <td>Pagado</td>
            <td>
              {% if c.pagado == True %}
                Pago
              {% else %}
                Debe
              {% endif %}
            </td>
          </tr>
          <tr>
            <td>Devuelto</td>
            <td>
              {% if c.devuelto == True %}
                Devuelto
              {% else %}
                No devuelto
              {% endif %}
            </td>
          </tr>
          <tr>
            <td>Observaciones</td>
            <td>
              <textarea name="observacion" id="observacion" cols="1" rows="4">
                {{c.observacion}}
              </textarea>
              <button id="guardar" type="button" class="button boton1" name="entrar" onclick="editarobservacion();">Guardar</button>
            </td

          </tr>
        </tbody>
      </table>
    </div>
 </div>
</div>
{% endblock %}
{% block contenido_ancho %}
<div class="off-canvas-content" data-off-canvas-content>
 <div class="row titulo large-10 large-offset-1 medium-10 medium-offset-1 small-12">
<div class="callout medium">
  <h4>Lista de productos comprados:</h4>
  <table id="listaproductos">
    <thead>
      <tr>
        <th width="5%">ID</th>
        <th width="">Producto</th>
        <th width="15%">Cantidad</th>
      </tr>
    </thead>
    <tbody>
      {%for p in productos%}
        <tr>
          <td>{{p.producto.pk}}</td>
          <td>{{p.producto.categoria}}-{{p.producto.modelo.marca}}-{{p.producto.modelo}}</td>
          <td>{{p.cantidad}}</td>
        </tr>
      {%endfor%}
    </tbody>
  </table>
</div>
</div>
</div>
{% endblock %}
{%block script%}
$( document ).ready(function() {
  obse = $("#observacion").val();
  obse = $.trim(obse);
  $("#observacion").val(obse);
  $("#observacion").focus();
});

function editarobservacion(){
  obse = $("#observacion").val();
  observacion = $.trim(obse);
  $.ajax({
    url: "observacion",
    dataType: "json",
    data: {'observacion':observacion},
    success: function(detalle){
      if(detalle=="ok"){
        window.location.replace("/consignaciones/listar");
      }
      else{
        console.log("hay que implementar un div para mostrat error");
        console.log(detalle);
      }
    }
  });
}

function editarconsignacionespagado(){
  $.ajax({
    url: "/consignaciones/editar/{{c.pk}}/pagado",
    dataType: "json",
    success: function(detalle){
      if(detalle=="ok"){
        window.location.replace("/consignaciones/listar");
        console.log("debe redirigir a ventas");
      }
      else{
        console.log("hay que implementar un div para mostrat error");
        console.log(detalle);
      }
    }
  });
}

function pagoydevolvio(){
  $.ajax({
    url: "/consignaciones/editar/{{c.pk}}/pagoydevolvio",
    dataType: "json",
    success: function(detalle){
      if(detalle=="ok"){
        window.location.replace("/consignaciones/listar");
        console.log("debe redirigir a ventas");
      }
      else{
        console.log("hay que implementar un div para mostrat error");
        console.log(detalle);
      }
    }
  });
}

function editarconsignacionesdevuelto(){
  $.ajax({
    url: "/consignaciones/editar/{{c.pk}}/devuelto",
    dataType: "json",
    success: function(detalle){
      if(detalle=="ok"){
        window.location.replace("/consignaciones/listar");
      }
      else{
        console.log("hay que implementar un div para mostrat error");
        console.log(detalle);
      }
    }
  });
}
{% endblock %}

templates/consignaciones/eliminar.html
{% extends 'inicio/base.html' %}
{% block contenido %}
<div class="off-canvas-content" data-off-canvas-content>
 <div class="row titulo large-8 large-offset-2 medium-8 medium-offset-2 small-12">
   <form class="" action="#" method="POST">{% csrf_token %}
     <h3>Detalles de la Consignacion</h3>
       {% if detalle %}
         {% if detalle != "0" %}
         <h5 class="error">
           {{detalle}}
         </h5>
         {% endif %}
       {% endif %}
       <div class="callout medium">
         <h4>Datos generales</h4>
         <table>
           <tbody>
             <tr>
               <td>Cliente</td>
               <td>{{c.personas.nombres|upper}}</td>
             </tr>
             <tr>
               <td>Fecha</td>
               <td>{{c.fecha|date:'d/m/Y H:i:s'}}</td>
             </tr>
             <tr>
               <td>Pagado</td>
               <td>
                 {% if c.pagado == True %}
                   <span class="alerta" >Pagado</span>
                 {% else %}
                   <span class="error" >Debe</span>
                 {% endif %}
               </td>
             </tr>
             <tr>
               <td>Devuelto</td>
               <td>
                 {% if c.devuelto == True %}
                   <span class="alerta" >Devuelto</span>
                 {% else %}
                   <span class="error" >No devuelto</span>
                 {% endif %}
               </td>
             </tr>
           </tbody>
         </table>
       </div>

       {% endblock %}
       {% block contenido_ancho %}
       <div class="off-canvas-content" data-off-canvas-content>
        <div class="row titulo large-10 large-offset-1 medium-10 medium-offset-1 small-12">
       <div class="callout medium">
         <h4>Lista de productos comprados:</h4>
         <table id="listaproductos">
           <thead>
             <tr>
               <th width="5%">ID</th>
               <th width="">Producto</th>
               <th width="15%">Cantidad</th>
             </tr>
           </thead>
           <tbody>
             {%for p in productos%}
               <tr>
                 <td>{{p.producto.pk}}</td>
                 <td>{{p.producto.categoria}}-{{p.producto.modelo.marca}}-{{p.producto.modelo}}</td>
                 <td>{{p.cantidad}}</td>
               </tr>
             {%endfor%}
           </tbody>
         </table>
         <button type="submit" class="button boton1" name="eliminar">Eliminar</button>
       </div>
       </div>
       </div>
     </form>
   </div>
 </div>
{% endblock %}