inicio/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout_then_login
from django.views.generic  import TemplateView
from . import views
from .views import *
urlpatterns = [
    url(r'^$', login, {'template_name': 'inicio/index.html'}, name='home'),
    url(r'^salir/$', logout_then_login, name='salir'),
    url(r'^comisiones/agregar$', agregarcomision, name='agregarcomision'),
    url(r'^comisiones/listar$', listarcomisiones, name='comisiones_listar'),
    url(r'^comisiones/ranking$', rankingcomisiones, name='ranking_listar'),
    #url(r'^comisiones/buscar-ajax$', buscarventas, name='ventas_buscar_ajax'),
    url(r'^comisiones/editar/(?P<pk>[0-9]+)/$', editarcomision, name='comisiones_editar'),
    url(r'^comisiones/eliminar/(?P<pk>[0-9]+)/$', eliminarcomision, name='comisiones_eliminar'),
    url(r'^caja/listar$', listarcajas, name='caja_listar'),
    url(r'^comisiones/reportes$', reportecomisiones, name='reporte_comisiones'),
    url(r'^comisiones/reportepersona$', reportecomsionpersona, name='reportecomisionpersona'),
    url(r'^caja/abrir$', abrircaja, name='caja_abrir'),
    url(r'^caja/cerrar$', cerrarcaja, name='caja_cerrar'),
    url(r'^caja/resumen/(?P<pk>[0-9]+)/$', resumencaja, name='resumen_caja'),
    url(r'^usuario/agregar$', agregarusuario, name='usuario_agregar'),
    ]

modasmartphonesac/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('inicio.urls')),
    url(r'', include('personas.urls')),
    url(r'', include('productos.urls')),
    url(r'', include('compras.urls')),
    url(r'', include('consignaciones.urls')),
    url(r'', include('ventas.urls')),
    url(r'', include('salidas.urls')),
    url(r'', include('desbloqueos.urls')),
]

salidas/urls.py
from django.conf.urls import include, url
from .views import *

urlpatterns = [
    url(r'^perdidas/agregar$', agregarperdida, name='agregarperdida'),
    url(r'^perdidas/listar$', listarperdidas, name='perdidas_listar'),
    #url(r'^ventas/buscar-ajax$', buscarventas, name='ventas_buscar_ajax'),
    url(r'^perdidas/editar/(?P<pk>[0-9]+)/$', editarperdida, name='perdidas_editar'),
    url(r'^perdidas/eliminar/(?P<pk>[0-9]+)/$', eliminarperdida, name='perdidas_eliminar'),
    url(r'^gastos/agregar$', agregargasto, name='agregargasto'),
    url(r'^gastos/listar$', listargastos, name='gastos_listar'),
    #url(r'^gastos/buscar-ajax$', buscarventas, name='ventas_buscar_ajax'),
    url(r'^gastos/editar/(?P<pk>[0-9]+)/$', editargasto, name='gastos_editar'),
    url(r'^gastos/eliminar/(?P<pk>[0-9]+)/$', eliminargasto, name='gastos_eliminar'),
    ]

salidas/models.py
from __future__ import unicode_literals
from django.db.models.signals import *
from django.dispatch import receiver
from django.shortcuts import get_object_or_404
from django.db import models
from productos.models import Producto
from compras.models import detalle_compra

# Create your models here.
class Perdida(models.Model):
    fecha = models.DateField()
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='Perdida2producto')
    cantidad = models.IntegerField(default=1)
    observacion = models.CharField(max_length=100)
    def __str__(self):
        return str(self.fecha)

class Pago(models.Model):
    fecha = models.DateField()
    monto = models.DecimalField(max_digits=6, decimal_places=2)
    acreedor = models.CharField(max_length=70)
    vencido = models.BooleanField(default=False)
    pagado = models.BooleanField(default=False)
    observacion = models.CharField(max_length=50)
    def __str__(self):
        return self.acreedor + str(self.fecha)

class Gasto(models.Model):
    fecha = models.DateField()
    monto = models.DecimalField(max_digits=6, decimal_places=2)
    observacion = models.CharField(max_length=50)
    def __str__(self):
        return str(self.fecha)

def descontardc(prod, cant):
    dcs = detalle_compra.objects.filter(producto=prod, activo=True).order_by('compra__fecha')
    for dc in dcs:
        stock = dc.cantidad - dc.unidades_fuera
        if cant>0:
            if stock >= cant:
                dc.unidades_fuera += int(cant)
                cant = 0
            else:
                cant -= stock
                dc.unidades_fuera = dc.cantidad
            if dc.cantidad == dc.unidades_fuera:
                dc.activo=False
            dc.save()

def regresardc(prod, cant):
        dcs = detalle_compra.objects.filter(producto=prod).order_by('compra__fecha')
        for dc in dcs:
            if cant > 0:
                if cant>dc.unidades_fuera:
                    cant -=dc.unidades_fuera
                else:
                    dc.unidades_fuera -=cant
                    cant = 0
                if dc.cantidad == dc.unidades_fuera:
                    dc.activo = False
                else:
                    dc.activo = True
                dc.save()

@receiver(post_save, sender=Perdida)
def descontarstock(sender, instance, **kwargs):
    if kwargs['created']:
        pk = instance.producto.pk
        nuevo_stock = instance.cantidad
        producto = get_object_or_404(Producto, pk=pk)
        producto.stock-= int(nuevo_stock)
        descontardc(producto, nuevo_stock)
        producto.save()

@receiver(post_delete, sender=Perdida)
def retornarstock(sender, instance, **kwargs):
    pk = instance.producto.pk
    nuevo_stock = instance.cantidad
    producto = get_object_or_404(Producto, pk=pk)
    producto.stock+= int(nuevo_stock)
    regresardc(producto,nuevo_stock)
    producto.save()

salidas/forms.py
from django.forms import *
from .models import *
import datetime
from django.forms import *
from productos.models import Producto
from django.core.validators import RegexValidator

def getfecha():
    return datetime.date.today().strftime("%d/%m/%Y")

class PerdidaForm(forms.Form):
    fecha = DateField(input_formats=['%d/%m/%Y'],widget = TextInput(
        attrs={'placeholder':'dd/mm/aaaa'}), initial = getfecha())
    producto = CharField(widget=HiddenInput)
    cantidad = IntegerField()
    observacion = CharField(max_length=50, widget = Textarea(
        attrs={'placeholder':'Ingrese datos extras'}), required=False)

class GastoForm(forms.Form):
    fecha = DateField(input_formats=['%d/%m/%Y'],widget = TextInput(
        attrs={'placeholder':'dd/mm/aaaa'}), initial = getfecha())
    monto = DecimalField(decimal_places=2)
    observacion = CharField(max_length=50, widget = Textarea(
        attrs={'placeholder':'Ingrese datos extras'}), required=False)

salidas/views.py
from django.shortcuts import render
from datetime import datetime
from django.shortcuts import render, get_object_or_404, redirect
from personas.models import Personas
from productos.models import Producto
from django.core.urlresolvers import reverse_lazy
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
import datetime
import time
from django.contrib.auth.decorators import user_passes_test

@login_required
@user_passes_test(lambda u: u.is_staff, login_url='/consignaciones/listar')
def agregarperdida(request):
    if request.method == 'POST':
        form = PerdidaForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = Perdida()
                pk = form.cleaned_data['producto']
                c.producto = get_object_or_404(Producto, pk=pk)
                c.fecha = form.cleaned_data['fecha']
                c.cantidad = form.cleaned_data['cantidad']
                c.observacion = form.cleaned_data['observacion']
                c.save()
        except Exception as e:
             detalle = "Error: " + str(e)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'salidas/perdidas/agregar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('perdidas_listar'))
    else:
        form = PerdidaForm()
        return render(request, 'salidas/perdidas/agregar.html', {'form': form})

@login_required
@user_passes_test(lambda u: u.is_staff, login_url='/consignaciones/listar')
def listarperdidas(request):
    lista = Perdida.objects.all().order_by('-fecha')
    page = request.GET.get('page')
    paginator = Paginator(lista, 10)
    try:
        lista = paginator.page(page)
    except PageNotAnInteger:
        lista = paginator.page(1)
    except EmptyPage:
        lista = paginator.page(1)
    return render(request, 'salidas/perdidas/listar.html', { 'lista': lista, 'paginator':paginator })

@login_required
@user_passes_test(lambda u: u.is_staff, login_url='/consignaciones/listar')
def editarperdida(request, pk):
    if request.method == 'POST':
        form = PerdidaForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = get_object_or_404(Perdida, pk=pk)
                pk = form.cleaned_data['producto']
                c.producto = get_object_or_404(Producto, pk=pk)
                c.fecha = form.cleaned_data['fecha']
                c.cantidad = form.cleaned_data['cantidad']
                c.observacion = form.cleaned_data['observacion']
                c.save()
        except Exception, e:
            detalle = "Error: " + str(e)
            print(detalle)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'salidas/perdidas/editar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('perdidas_listar'))
    else:
        c = get_object_or_404(Perdida, pk=pk)
        nompro = c.producto.categoria.nombre + "-" + c.producto.modelo.marca.nombre + "-" + c.producto.modelo.nombre
        form = PerdidaForm(initial={'fecha':c.fecha.strftime("%d/%m/%Y"),
            'producto': c.producto.pk , 'cantidad':c.cantidad, 'observacion': c.observacion})
        return render(request, 'salidas/perdidas/editar.html', {'form': form, 'nompro':nompro})

@login_required
@user_passes_test(lambda u: u.is_staff, login_url='/consignaciones/listar')
def eliminarperdida(request, pk):
    c = get_object_or_404(Perdida, pk=pk)
    detalle = 0
    if request.method == 'POST':
        try:
            c.delete()
        except Exception, e:
            detalle = "Error: " + str(e)
        finally:
            if detalle != 0:
                return render(request, 'salidas/perdidas/eliminar.html', {'perdida': c, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('perdidas_listar'))
    else:
        nompro = c.producto.categoria.nombre + "-" + c.producto.modelo.marca.nombre + "-" + c.producto.modelo.nombre
        return render(request, 'salidas/perdidas/eliminar.html', {'c': c, 'nompro':nompro})

#----------------------------------------------------------------------------------------------------

@login_required
def agregargasto(request):
    if request.method == 'POST':
        form = GastoForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = Gasto()
                c.fecha = form.cleaned_data['fecha']
                c.monto = form.cleaned_data['monto']
                c.observacion = form.cleaned_data['observacion']
                c.save()
        except Exception as e:
             detalle = "Error: " + str(e)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'salidas/gastos/agregar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('gastos_listar'))
    else:
        form = GastoForm()
        return render(request, 'salidas/gastos/agregar.html', {'form': form})

@login_required
@user_passes_test(lambda u: u.is_staff, login_url='/consignaciones/listar')
def listargastos(request):
    lista = Gasto.objects.all().order_by('-fecha')
    page = request.GET.get('page')
    paginator = Paginator(lista, 10)
    try:
        lista = paginator.page(page)
    except PageNotAnInteger:
        lista = paginator.page(1)
    except EmptyPage:
        lista = paginator.page(1)
    return render(request, 'salidas/gastos/listar.html', { 'lista': lista, 'paginator':paginator })

@login_required
@user_passes_test(lambda u: u.is_staff, login_url='/consignaciones/listar')
def editargasto(request, pk):
    if request.method == 'POST':
        form = GastoForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = get_object_or_404(Gasto, pk=pk)
                c.fecha = form.cleaned_data['fecha']
                c.monto = form.cleaned_data['monto']
                c.observacion = form.cleaned_data['observacion']
                c.save()
        except Exception, e:
            detalle = "Error: " + str(e)
            print(detalle)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'salidas/gastos/editar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('gastos_listar'))
    else:
        c = get_object_or_404(Gasto, pk=pk)
        form = GastoForm(initial={'fecha':c.fecha.strftime("%d/%m/%Y"), 'monto':c.monto, 'observacion':c.observacion})
        return render(request, 'salidas/gastos/editar.html', {'form': form})

@login_required
@user_passes_test(lambda u: u.is_staff, login_url='/consignaciones/listar')
def eliminargasto(request, pk):
    c = get_object_or_404(Gasto, pk=pk)
    detalle = 0
    if request.method == 'POST':
        try:
            c.delete()
        except Exception, e:
            detalle = "Error: " + str(e)
        finally:
            if detalle != 0:
                return render(request, 'salidas/gastos/eliminar.html', {'c': c, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('gastos_listar'))
    else:
        return render(request, 'salidas/gastos/eliminar.html', {'c': c})

def rangogastos(fec1, fec2):
    total=0
    lista = Gasto.objects.filter(fecha__range=[fec1,fec2])
    for c in lista:
        total += c.monto
    return total

templates/salidas/perdidas/agregar.html
{% extends 'inicio/base.html' %}
{% block contenido %}
<div class="off-canvas-content" data-off-canvas-content>
 <div class="row titulo large-8 large-offset-2 medium-8 medium-offset-2 small-12">
   <form id="form" class="" action="#" method="post">{% csrf_token %}
      <h3>Agregar Perdida</h3>
        {% if detalle %}
          {% if detalle != "0" %}
          <h5 class="error">
            {{detalle}}
          </h5>
          {% endif %}
        {% endif %}
      <label for="id_fecha">Fecha: (Requerido)</label>
      {{form.fecha}}
      <div class="input-group">
        {{form.producto}}
        <a href="#" class="botonopenmodal input-group-button" id="abrirmodal2" data-open="exampleModal2"><i class="material-icons">search</i></a>
        <input type="text" class=" input-group-field" readonly placeholder="Seleccione un producto" id="producto" name="" value="">
      </div>
      <label for="cantidad">Cantidad</label>
      {{form.cantidad}}
      <label for="id_observacion">Observaciones: (Opcional)</label>
      {{form.observacion}}
      <button id="guardar" type="submit" class="button boton1" name="entrar">Guardar</button>
<!--MODAL PARA PRODUCTO-->
  <div class="reveal titulo" id="exampleModal2" data-reveal>
   <h3>Seleccionar Producto</h3>
   <div class="input-group input-group-rounded columns large-6 medium-4">
     <span class="input-group-label"><i class="material-icons">search</i></span>
     <input type="text" id="buscadorproducto" name="buscador" class="buscador input-group-field" placeholder="Buscar producto">
   </div>
     <table class="table-scroll" id="tablaproducto">
       <thead>
         <tr>
           <th>Categoria</th>
           <th>Marca</th>
           <th>Modelo</th>
           <th>Seleccionar</th>
         </tr>
       </thead>
       <tbody>
       </tbody>
     </table>
   <button class="close-button" data-close aria-label="Close modal" type="button">
     <span aria-hidden="true">&times;</span>
   </button>
 </div>
<!--MODAL PARA PRODUCTO-->
</div>
{% endblock %}
{%block script%}
$( document ).ready(function() {
  $("#id_fecha").mask("99/99/9999");
  $("#abrirmodal2").focus();
});
$('#buscadorproducto').change(function(){
  $("#tablaproducto tbody tr").remove();
  a = $("#buscadorproducto").val().length;
  if(a>1){
    texto = $("#buscadorproducto").val();
    $.ajax({
      data: {'term':texto},
      url: "/productos/buscar-ajax2",
      type: "get",
      success: function(data){
        for(var i = 0; i<data.length; i++){
          categoria = data[i].categoria.replace(/\s+/g, '-');
          modelo = data[i].modelo.replace(/\s+/g, '-');
          marca = data[i].marca.replace(/\s+/g, '-');
          nombrecompleto = categoria + '-' + marca + '-' + modelo;
          if(data.length==1){
            seleccionar2(data[i].pk, nombrecompleto);
          }
          nuevafila = "<tr>";
          nuevafila +="<td>" + data[i].categoria + "</td>" +
                      "<td>" + data[i].marca + "</td>" +
                      "<td>" + data[i].modelo + "</td>" +
                      "<td><a href=javascript:seleccionar2("+ data[i].pk + ",'" + nombrecompleto +"');><i class=material-icons>thumb_up</i></a></td></tr>";
          $("#tablaproducto").append(nuevafila);
       }

      }
    });
  }
});
function seleccionar2(id, modelo){
  $("#id_producto").val(id);
  $("#producto").val(modelo);
  $("#exampleModal2").foundation('close');
  $("#buscadorproducto").val('');
  $("#tablaproducto tbody tr").remove();
  $("#id_cantidad").focus();
}
{% endblock %}

templates/salidas/perdidas/editar.html
{% extends 'inicio/base.html' %}
{% block contenido %}
<div class="off-canvas-content" data-off-canvas-content>
 <div class="row titulo large-8 large-offset-2 medium-8 medium-offset-2 small-12">
   <form id="form" class="" action="#" method="post">{% csrf_token %}
      <h3>Agregar Perdida</h3>
        {% if detalle %}
          {% if detalle != "0" %}
          <h5 class="error">
            {{detalle}}
          </h5>
          {% endif %}
        {% endif %}
      <label for="id_fecha">Fecha: (Requerido)</label>
      {{form.fecha}}
      <div class="input-group">
        {{form.producto}}
        <a href="#" class="botonopenmodal input-group-button" id="abrirmodal2" data-open="exampleModal2"><i class="material-icons">search</i></a>
        <input type="text" class=" input-group-field" readonly placeholder="Seleccione un producto" id="producto" name="" value="{{nompro}}">
      </div>
      <label for="cantidad">Cantidad</label>
      {{form.cantidad}}
      <label for="id_observacion">Observaciones: (Opcional)</label>
      {{form.observacion}}
      <button id="guardar" type="submit" class="button boton1" name="entrar">Guardar</button>
<!--MODAL PARA PRODUCTO-->
  <div class="reveal titulo" id="exampleModal2" data-reveal>
   <h3>Seleccionar Producto</h3>
   <div class="input-group input-group-rounded columns large-6 medium-4">
     <span class="input-group-label"><i class="material-icons">search</i></span>
     <input type="text" id="buscadorproducto" name="buscador" class="buscador input-group-field" placeholder="Buscar producto">
   </div>
     <table class="table-scroll" id="tablaproducto">
       <thead>
         <tr>
           <th>Categoria</th>
           <th>Marca</th>
           <th>Modelo</th>
           <th>Seleccionar</th>
         </tr>
       </thead>
       <tbody>
       </tbody>
     </table>
   <button class="close-button" data-close aria-label="Close modal" type="button">
     <span aria-hidden="true">&times;</span>
   </button>
 </div>
<!--MODAL PARA PRODUCTO-->
</div>
{% endblock %}
{%block script%}
$( document ).ready(function() {
  $("#id_fecha").mask("99/99/9999");
  $("#abrirmodal2").focus();
});
$('#buscadorproducto').change(function(){
  $("#tablaproducto tbody tr").remove();
  a = $("#buscadorproducto").val().length;
  if(a>1){
    texto = $("#buscadorproducto").val();
    $.ajax({
      data: {'term':texto},
      url: "/productos/buscar-ajax2",
      type: "get",
      success: function(data){
        for(var i = 0; i<data.length; i++){
          categoria = data[i].categoria.replace(/\s+/g, '-');
          modelo = data[i].modelo.replace(/\s+/g, '-');
          marca = data[i].marca.replace(/\s+/g, '-');
          nombrecompleto = categoria + '-' + marca + '-' + modelo;
          if(data.length==1){
            seleccionar2(data[i].pk, nombrecompleto);
          }
          nuevafila = "<tr>";
          nuevafila +="<td>" + data[i].categoria + "</td>" +
                      "<td>" + data[i].marca + "</td>" +
                      "<td>" + data[i].modelo + "</td>" +
                      "<td><a href=javascript:seleccionar2("+ data[i].pk + ",'" + nombrecompleto +"');><i class=material-icons>thumb_up</i></a></td></tr>";
          $("#tablaproducto").append(nuevafila);
       }

      }
    });
  }
});
function seleccionar2(id, modelo){
  $("#id_producto").val(id);
  $("#producto").val(modelo);
  $("#exampleModal2").foundation('close');
  $("#buscadorproducto").val('');
  $("#tablaproducto tbody tr").remove();
  $("#id_cantidad").focus();
}
{% endblock %}

templates/salidas/perdidas/eliminar.html
{% extends 'inicio/base.html' %}
{% block contenido %}
<div class="off-canvas-content" data-off-canvas-content>
 <div class="row titulo large-8 large-offset-2 medium-8 medium-offset-2 small-12">
   <form class="" action="#" method="POST">{% csrf_token %}
     <h3>Detalles de la Compra</h3>
       {% if detalle %}
         {% if detalle != "0" %}
         <h5 class="error">
           {{detalle}}
         </h5>
         {% endif %}
       {% endif %}
       <div class="callout medium">
         <h4>Datos generales</h4>
         <table>
           <tbody>
             <tr>
               <td>Proveedor</td>
               <td>{{c.personas.nombres|upper}}</td>
             </tr>
             <tr>
               <td>Fecha</td>
               <td>{{c.fecha|date:'d/m/Y'}}</td>
             </tr>
             <tr>
               <td>Con Factura</td>
               <td>
                 {% if c.facturado == True %}
                   SI
                 {% else %}
                   NO
                 {% endif %}
               </td>
             </tr>
             <tr>
               <td>Tipo de pago</td>
               <td>
                 {% if c.pago == True %}
                   EN EFECTICO
                 {% else %}
                   CREDITO
                 {% endif %}
               </td>
             </tr>
           </tbody>
         </table>
       </div>

       {% endblock %}
       {% block contenido_ancho %}
       <div class="off-canvas-content" data-off-canvas-content>
        <div class="row titulo large-10 large-offset-1 medium-10 medium-offset-1 small-12">
       <div class="callout medium">
         <h4>Lista de productos comprados:</h4>
         <table id="listaproductos">
           <thead>
             <tr>
               <th width="5%">ID</th>
               <th width="">Producto</th>
               <th width="15%">Costo</th>
               <th width="15%">Cantidad</th>
             </tr>
           </thead>
           <tbody>
             {%for p in productos%}
               <tr>
                 <td>{{p.producto.pk}}</td>
                 <td>{{p.producto.categoria}}-{{p.producto.modelo.marca}}-{{p.producto.modelo}}</td>
                 <td>{{p.costo}}</td>
                 <td>{{p.cantidad}}</td>
               </tr>
             {%endfor%}
           </tbody>
         </table>
         <button type="submit" class="button boton1" name="eliminar">Eliminar</button>
       </div>
       </div>
       </div>
     </form>
   </div>
 </div>
{% endblock %}

templates/salidas/perdidas/listar.html
{% extends 'inicio/base.html' %}
{% block contenido %}
<div class="off-canvas-content" data-off-canvas-content>
  <div class="callout clearfix">
    <a href="/perdidas/agregar" class="button float-left">Agregar nueva Perdida</a>
  </div>
  <div class="row titulo large-10 large-offset-1 medium-10 medium-offset-1 small-12">
    <div class="row panel-clearfix">
      <h3 class="columns large-8 medium-6 small-12 left">Listado Perdidas</h3>
      <div class="columns large-4 right medium-6 small-12">
        <!--<div class="input-group input-group-rounded columns large-6 medium-4">
          <span class="input-group-label"><i class="material-icons">search</i></span>
          <input type="text" id="texto" name="buscador" class="buscador input-group-field" placeholder="Buscar Perdida" id="buscador">
        </div>-->
        <a href="/consignaciones/reportes" class="button float-left">Reportes</a>
      </div>
    </div>
      <div class="table-scroll">
        <table id="tabla">
          <thead>
            <tr>
              <th>Categoria</th>
              <th>Marca</th>
              <th>Modelo</th>
              <th>Fecha</th>
              <th>Cantidad</th>
              <th>Observacion</th>
              <th>Editar</th>
              <th>Eliminar</th>
            </tr>
          </thead>
          <tbody>
        {% for c in lista %}
            <tr>
              <td>{{c.producto.categoria.nombre}}</td>
              <td>{{c.producto.modelo.marca.nombre}}</td>
              <td>{{c.producto.modelo.nombre}}</td>
              <td>{{c.fecha|date:'d/m/Y'}}</td>
              <td>{{c.cantidad}}</td>
              <td>{{c.observacion}}</td>
              <td><a href="editar/{{c.pk}}"><i class="material-icons">mode_edit</i></a></td>
              <td><a href="eliminar/{{c.pk}}"> <i class="material-icons">delete</i></a> </td>
            </tr>
        {% endfor %}
          </tbody>
        </table>
        </div>
        {% if paginator.num_pages > 1%}
          <ul class="pagination text-center" role="navigation" aria-label="Pagination">
            {% for i in paginator.page_range %}
              {% if i != lista.number  %}
              <li class="paginas"><a href="?page={{i}}" aria-label="Page {{i}}">{{i}}</a></li>
              {% else %}
              <li class="paginas">{{i}}</li>
              {% endif %}
            {% endfor %}
          </ul>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block script %}
  $(document).ready(function() {
    $('#texto').focus();
  });
  $('#texto').change(function(){
    a = $("#texto").val().length;
    if(a>2){
      $("#tabla tbody tr").remove();
      texto = $("#texto").val();
      nuevafila = "<tr>"
      $.ajax({
				data: {'term':texto},
				url: "/compras/buscar-ajax",
				type: "get",
				success: function(data){
          for(var i = 0; i<data.length; i++){
            var fec = new Date(data[i].fecha);
						var fecha = fec.getDate() + '/' + (fec.getMonth() + 1) + '/' + fec.getFullYear();
            var facturado="";
            if(data[i].facturado==true){
              facturado = "Con Factura";
            }
            else{
              facturado = "Sin Factura";
            }
            var pago="";
            if(data[i].pago==true){
              pago = "Efectivo";
            }
            else{
              pago = "Credito";
            }
            nuevafila +="<td>" + data[i].proveedor + "</td>" +
                        "<td>" + fecha + "</td>" +
                        "<td>" + facturado + "</td>" +
                        "<td>" + pago + "</td>" +
                        '<td><a href="editar/'+ data[i].pk +'"> <i class="material-icons">mode_edit</i></a></td>'+
                        '<td><a href="eliminar/'+ data[i].pk +'"> <i class="material-icons">delete</i></a> </td></tr>';
           $("#tabla").append(nuevafila);
         }
        }
      });
    }
    else if(a==0){
      window.location.replace("/ventas/listar?page=1");
    }
  });
{% endblock %}