inicio/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout_then_login
from django.views.generic  import TemplateView
from . import views
from .views import *
urlpatterns = [
    url(r'^$', login, {'template_name': 'inicio/index.html'}, name='home'),
    url(r'^salir/$', logout_then_login, name='salir'),
    url(r'^comisiones/agregar$', agregarcomision, name='agregarcomision'),
    url(r'^comisiones/listar$', listarcomisiones, name='comisiones_listar'),
    url(r'^comisiones/ranking$', rankingcomisiones, name='ranking_listar'),
    #url(r'^comisiones/buscar-ajax$', buscarventas, name='ventas_buscar_ajax'),
    url(r'^comisiones/editar/(?P<pk>[0-9]+)/$', editarcomision, name='comisiones_editar'),
    url(r'^comisiones/eliminar/(?P<pk>[0-9]+)/$', eliminarcomision, name='comisiones_eliminar'),
    url(r'^caja/listar$', listarcajas, name='caja_listar'),
    url(r'^comisiones/reportes$', reportecomisiones, name='reporte_comisiones'),
    url(r'^comisiones/reportepersona$', reportecomsionpersona, name='reportecomisionpersona'),
    url(r'^caja/abrir$', abrircaja, name='caja_abrir'),
    url(r'^caja/cerrar$', cerrarcaja, name='caja_cerrar'),
    url(r'^caja/resumen/(?P<pk>[0-9]+)/$', resumencaja, name='resumen_caja'),
    url(r'^usuario/agregar$', agregarusuario, name='usuario_agregar'),
    ]

modasmartphonesac/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('inicio.urls')),
    url(r'', include('personas.urls')),
    url(r'', include('productos.urls')),
    url(r'', include('compras.urls')),
    url(r'', include('consignaciones.urls')),
    url(r'', include('ventas.urls')),
    url(r'', include('salidas.urls')),
    url(r'', include('desbloqueos.urls')),
]

productos/urls.py
from django.conf.urls import include, url
from .views import *

urlpatterns = [
    url(r'^categorias/agregar$', agregarcategoria, name='categoria_agregar'),
    url(r'^categorias/listar$', listarcategorias, name='categorias_listar'),
    url(r'^categorias/buscar-ajax$', buscarcategorias, name='categorias_buscar_ajax'),
    url(r'^categorias/editar/(?P<pk>[0-9]+)/$', editarcategorias, name='categorias_editar'),
    url(r'^categorias/eliminar/(?P<pk>[0-9]+)/$', eliminarcategorias, name='categorias_eliminar'),
    url(r'^marcas/agregar$', agregarmarca, name='marca_agregar'),
    url(r'^marcas/listar$', listarmarcas, name='marcas_listar'),
    url(r'^marcas/buscar-ajax$', buscarmarcas, name='marcas_buscar_ajax'),
    url(r'^marcas/editar/(?P<pk>[0-9]+)/$', editarmarcas, name='marcas_editar'),
    url(r'^marcas/eliminar/(?P<pk>[0-9]+)/$', eliminarmarcas, name='marcas_eliminar'),
    url(r'^modelos/agregar$', agregarmodelo, name='modelo_agregar'),
    url(r'^modelos/listar$', listarmodelos, name='modelos_listar'),
    url(r'^modelos/buscar-ajax$', buscarmodelos, name='modelos_buscar_ajax'),
    url(r'^modelos/editar/(?P<pk>[0-9]+)/$', editarmodelos, name='modelos_editar'),
    url(r'^modelos/eliminar/(?P<pk>[0-9]+)/$', eliminarmodelos, name='modelos_eliminar'),
    url(r'^precios/agregar$', agregarprecio, name='precio_agregar'),
    url(r'^precios/listar$', listarprecios, name='precios_listar'),
    url(r'^precios/buscar-ajax$', buscarprecios, name='precios_buscar_ajax'),
    url(r'^precios/editar/(?P<pk>[0-9]+)/$', editarprecios, name='precios_editar'),
    url(r'^precios/eliminar/(?P<pk>[0-9]+)/$', eliminarprecios, name='precios_eliminar'),
    url(r'^almacenes/agregar$', agregaralmacen, name='almacen_agregar'),
    url(r'^almacenes/listar$', listaralmacenes, name='almacenes_listar'),
    url(r'^almacenes/buscar-ajax$', buscaralmacenes, name='almacenes_buscar_ajax'),
    url(r'^almacenes/editar/(?P<pk>[0-9]+)/$', editaralmacenes, name='almacenes_editar'),
    url(r'^almacenes/eliminar/(?P<pk>[0-9]+)/$', eliminaralmacenes, name='almacenes_eliminar'),
    url(r'^productos/agregar$', agregarproducto, name='producto_agregar'),
    url(r'^productos/listar$', listarproductos, name='productos_listar'),
    url(r'^productos/buscar-ajax$', buscarproductos, name='productos_buscar_ajax'),
    url(r'^productos/buscar-ajax2$', buscarproductos2, name='productos_buscar_ajax2'),
    url(r'^productos/editar/(?P<pk>[0-9]+)/$', editarproductos, name='productos_editar'),
    url(r'^productos/eliminar/(?P<pk>[0-9]+)/$', eliminarproductos, name='productos_eliminar'),
    url(r'^sku/agregar$', agregarsku, name='sku_agregar'),
    url(r'^sku/listar$', listarsku, name='sku_listar'),
    url(r'^sku/buscar-ajax$', buscarsku, name='sku_buscar_ajax'),
    url(r'^sku/editar/(?P<pk>[0-9]+)/$', editarsku, name='sku_editar'),
    url(r'^sku/eliminar/(?P<pk>[0-9]+)/$', eliminarsku, name='sku_eliminar'),
    ]

productos/models.py
from __future__ import unicode_literals

from django.db import models

class Marca(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.nombre

class Modelo(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    marca = models.ForeignKey('Marca',on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=70, unique=True)
    def __str__(self):
        return self.nombre

class Precio(models.Model):
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)
    modelo = models.ForeignKey('Modelo', on_delete=models.CASCADE)
    mayor = models.DecimalField(max_digits=6, decimal_places=2)
    punto = models.DecimalField(max_digits=6, decimal_places=2)
    cliente = models.DecimalField(max_digits=6, decimal_places=2)
    def __str__(self):
        return self.categoria.nombre + self.modelo.nombre

class Producto(models.Model):
    modelo = models.ForeignKey('Modelo', on_delete=models.CASCADE)
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)
    precio = models.ForeignKey('Precio', on_delete=models.CASCADE)
    costo = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    stock_minimo = models.IntegerField(default=1)
    stock = models.IntegerField(default=0)
    barra = models.CharField(max_length=8, unique=True, blank=True, null=True)
    descripcion = models.CharField(max_length=70,blank=True, null=True, default="Nada")
    def __str__(self):
        return self.categoria.nombre + "-" + self.modelo.marca.nombre + " " + self.modelo.nombre

class Almacen(models.Model):
    nombre = models.CharField(max_length=70)
    def __str__(self):
        return self.nombre

class Perdida(models.Model):
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)
    fecha = models.DateField()

productos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
import json
from django.http import HttpResponse
from decimal import Decimal

@login_required
def agregarcategoria(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = Categoria()
                c.nombre = form.cleaned_data['nombre'].lower()
                c.save()
        except Exception as e:
             detalle = "Error: " + str(e)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'productos/categorias/agregar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('categorias_listar'))
    else:
        form = CategoriaForm()
        return render(request, 'productos/categorias/agregar.html', {'form': form})

@login_required
def listarcategorias(request):
    lista = Categoria.objects.all().order_by('nombre')
    page = request.GET.get('page')
    paginator = Paginator(lista, 10)
    try:
        clase = paginator.page(page)
    except PageNotAnInteger:
        clase = paginator.page(1)
    except EmptyPage:
        clase = paginator.page(1)
    return render(request, 'productos/categorias/listar.html', { 'categorias': clase, 'paginator':paginator })

@login_required
def buscarcategorias(request):
    if request.is_ajax():
        texto = request.GET['term'].lower()
        if texto is not None:
            clase = Categoria.objects.filter(Q(nombre__contains = texto))
            lista = []
            for c in clase:
				lista.append({'pk':c.pk,'nombre':c.nombre})
            data = json.dumps(lista)
            return HttpResponse(data, content_type='application/json')

@login_required
def editarcategorias(request, pk):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = Categoria.objects.get(id=pk)
                c.nombre = form.cleaned_data['nombre'].lower()
                c.save()
        except Exception, e:
            detalle = "Error: " + str(e)
            print(detalle)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'productos/categorias/editar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('categorias_listar'))
    else:
        c = get_object_or_404(Categoria, pk=pk)
        form = CategoriaForm(initial={'nombre':c.nombre})
        return render(request, 'productos/categorias/editar.html', {'form': form})

@login_required
def eliminarcategorias(request, pk):
    c = get_object_or_404(Categoria, pk=pk)
    detalle = 0
    if request.method == 'POST':
        try:
            c.delete()
        except Exception, e:
            detalle = "Error: " + str(e)
        finally:
            if detalle != 0:
                return render(request, 'productos/categorias/eliminar.html', {'c': c, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('categorias_listar'))
    else:
        return render(request, 'productos/categorias/eliminar.html', {'c': c})
#-------------------------------------------------------------------------------

@login_required
def agregarmarca(request):
    if request.method == 'POST':
        form = MarcaForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = Marca()
                c.nombre = form.cleaned_data['nombre'].lower()
                c.save()
        except Exception as e:
             detalle = "Error: " + str(e)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'productos/marcas/agregar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('marcas_listar'))
    else:
        form = MarcaForm()
        return render(request, 'productos/marcas/agregar.html', {'form': form})

@login_required
def listarmarcas(request):
    lista = Marca.objects.all().order_by('nombre')
    page = request.GET.get('page')
    paginator = Paginator(lista, 10)
    try:
        clase = paginator.page(page)
    except PageNotAnInteger:
        clase = paginator.page(1)
    except EmptyPage:
        clase = paginator.page(1)
    return render(request, 'productos/marcas/listar.html', { 'marcas': clase, 'paginator':paginator })

@login_required
def buscarmarcas(request):
    if request.is_ajax():
        texto = request.GET['term'].lower()
        if texto is not None:
            clase = Marca.objects.filter(Q(nombre__contains = texto))
            lista = []
            for c in clase:
				lista.append({'pk':c.pk,'nombre':c.nombre})
            data = json.dumps(lista)
            return HttpResponse(data, content_type='application/json')

@login_required
def editarmarcas(request, pk):
    if request.method == 'POST':
        form = MarcaForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = Marca.objects.get(id=pk)
                c.nombre = form.cleaned_data['nombre'].lower()
                c.save()
        except Exception, e:
            detalle = "Error: " + str(e)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'productos/marcas/editar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('marcas_listar'))
    else:
        c = get_object_or_404(Marca, pk=pk)
        form = MarcaForm(initial={'nombre':c.nombre})
        return render(request, 'productos/marcas/editar.html', {'form': form})

@login_required
def eliminarmarcas(request, pk):
    c = get_object_or_404(Marca, pk=pk)
    detalle = 0
    if request.method == 'POST':
        try:
            c.delete()
        except Exception, e:
            detalle = "Error: " + str(e)
        finally:
            if detalle != 0:
                return render(request, 'productos/marcas/eliminar.html', {'c': c, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('marcas_listar'))
    else:
        return render(request, 'productos/marcas/eliminar.html', {'c': c})
#-------------------------------------------------------------------------------
@login_required
def agregarmodelo(request):
    if request.method == 'POST':
        form = ModeloForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = Modelo()
                c.nombre = form.cleaned_data['nombre'].lower()
                c.marca = form.cleaned_data['marca']
                c.save()
        except Exception as e:
             detalle = "Error: " + str(e)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'productos/modelos/agregar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('modelos_listar'))
    else:
        form = ModeloForm()
        return render(request, 'productos/modelos/agregar.html', {'form': form})

@login_required
def listarmodelos(request):
    lista = Modelo.objects.all().order_by('marca__nombre', 'nombre')
    page = request.GET.get('page')
    paginator = Paginator(lista, 10)
    try:
        clase = paginator.page(page)
    except PageNotAnInteger:
        clase = paginator.page(1)
    except EmptyPage:
        clase = paginator.page(1)
    return render(request, 'productos/modelos/listar.html', { 'modelos': clase, 'paginator':paginator })

@login_required
def buscarmodelos(request):
    if request.is_ajax():
        texto = request.GET['term']
        if texto is not None:
            clase = Modelo.objects.filter(Q(nombre__contains = texto)| Q(marca__nombre__contains = texto)).order_by('marca__nombre', 'nombre')
            lista = []
            for c in clase:
				lista.append({'pk':c.pk,'nombre':c.nombre, 'marca': c.marca.nombre})
            data = json.dumps(lista)
            return HttpResponse(data, content_type='application/json')

@login_required
def editarmodelos(request, pk):
    if request.method == 'POST':
        form = ModeloForm(request.POST)
        detalle = 0
        try:
            if form.is_valid():
                c = Modelo.objects.get(id=pk)
                c.nombre = form.cleaned_data['nombre'].lower()
                c.marca = form.cleaned_data['marca']
                c.save()
        except Exception, e:
            detalle = "Error: " + str(e)
        finally:
            if detalle != 0 or form.is_valid() == False:
                return render(request, 'productos/modelos/editar.html', {'form': form, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('modelos_listar'))
    else:
        c = get_object_or_404(Modelo, pk=pk)
        form = ModeloForm(initial={'nombre':c.nombre, 'marca':c.marca})
        return render(request, 'productos/modelos/editar.html', {'form': form})

@login_required
def eliminarmodelos(request, pk):
    c = get_object_or_404(Modelo, pk=pk)
    detalle = 0
    if request.method == 'POST':
        try:
            c.delete()
        except Exception, e:
            detalle = "Error: " + str(e)
        finally:
            if detalle != 0:
                return render(request, 'productos/modelos/eliminar.html', {'c': c, 'detalle':detalle})
            else:
                return redirect(reverse_lazy('modelos_listar'))
    else:
        return render(request, 'productos/modelos/eliminar.html', {'c': c})

templates/productos/productos/agregar.html
{% extends 'inicio/base.html' %}
{% block contenido %}
<div class="off-canvas-content" data-off-canvas-content>
 <div class="row titulo large-8 large-offset-2 medium-8 medium-offset-2 small-12">
   <form class="" action="#" method="post">{% csrf_token %}
      <h3>Agregar Producto</h3>
      {% if form.errors %}
        <h5 class="error">Ha ocurrido un error</h5>
        {% for field in form %}
          {% for error in field.errors %}
            <h5 class="error">{{error|escape}}</h5>
          {% endfor %}
        {% endfor %}
      {% else %}
        {% if detalle %}
          {% if detalle != "0" %}
          <h5 class="error">
            {{detalle}}
          </h5>
          {% endif %}
        {% endif %}
      {% endif %}
      <label class="" for="id_categoria">Seleccione Categoria: (Requerido)</label>
      {{form.categoria}}
      <div class="input-group">
        <a href="#" class="botonopenmodal input-group-button" id="abrirmodal2" data-open="exampleModal2"><i class="material-icons">search</i></a>
        <input type="text" class=" input-group-field" readonly id="id_nombrecategoria" name="" value="">
        <div hidden id="errorcategoria" class="error">
          Debe seleccionar una Categoria.
        </div>
      </div>
      <label for="id_nombre">Seleccione Modelo: (Requerido)</label>
      {{form.modelo}}
      <div class="input-group">
        <a href="#" class="botonopenmodal input-group-button" id="abrirmodal" data-open="exampleModal1"><i class="material-icons">search</i></a>
        <input type="text" class=" input-group-field" readonly id="id_nombre" name="" value="">
      </div>
      <label for="id_nombre">Seleccione Precio: (Requerido)</label>
      {{form.precio}}
      <div class="input-group">
        <a href="#" class="botonopenmodal input-group-button" id="abrirmodal3" data-open="exampleModal3"><i class="material-icons">search</i></a>
        <input type="text" class=" input-group-field" readonly id="id_precios" name="" value="">
      </div>
      <label for="id_mayor">Stock Minimo: (Requerido)</label>
      {{form.stock_minimo}}
      <label for="id_descripcion">Descripcion: (opcional)</label>
      <textarea id="id_descripcion" name="id_descripcion" rows="2" cols="40"></textarea>
      <button type="submit" class="button boton1" name="entrar">Guardar</button>
   </form>
 </div>
 <!--MODAL PARA MODELOS-->
   <div class="reveal titulo" id="exampleModal1" data-reveal>
    <h3>Seleccionar Modelo</h3>
    <div class="input-group input-group-rounded columns large-6 medium-4">
      <span class="input-group-label"><i class="material-icons">search</i></span>
      <input type="text" id="texto" name="buscador" class="buscador input-group-field" placeholder="Buscar Modelo" id="buscador">
    </div>
      <table id="tabla">
        <thead>
          <tr>
            <th>Modelo</th>
            <th>Marca</th>
            <th>Seleccionar</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    <button class="close-button" data-close aria-label="Close modal" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<!--MODAL PARA MODELOS-->
<!--MODAL PARA CATEGORIAS-->
  <div class="reveal titulo" id="exampleModal2" data-reveal>
   <h3>Seleccionar Categoria</h3>
   <div class="input-group input-group-rounded columns large-6 medium-4">
     <span class="input-group-label"><i class="material-icons">search</i></span>
     <input type="text" id="categoria" name="buscador" class="buscador input-group-field" placeholder="Buscar Categoria" id="buscador">
   </div>
     <table id="tabla2">
       <thead>
         <tr>
           <th>Nombre</th>
           <th>Seleccionar</th>
         </tr>
       </thead>
       <tbody>
       </tbody>
     </table>
   <button class="close-button" data-close aria-label="Close modal" type="button">
     <span aria-hidden="true">&times;</span>
   </button>
  </div>
<!--MODAL PARA CATEGORIAS-->
<!--MODAL PARA PRECIOS-->
  <div class="reveal titulo" id="exampleModal3" data-reveal>
   <h3>Seleccionar Precio</h3>
   <div class="input-group input-group-rounded columns large-6 medium-4">
     <span class="input-group-label"><i class="material-icons">search</i></span>
     <input type="text" id="precio" name="buscador" class="buscador input-group-field" placeholder="Buscar Precio" id="buscador">
   </div>
     <table id="tabla3">
       <thead>
         <tr>
           <th>Categoria</th>
           <th>Marca</th>
           <th>Modelo</th>
           <th>Mayor</th>
           <th>Punto</th>
           <th>Cliente</th>
           <th>Seleccionar</th>
         </tr>
       </thead>
       <tbody>
       </tbody>
     </table>
   <button class="close-button" data-close aria-label="Close modal" type="button">
     <span aria-hidden="true">&times;</span>
   </button>
  </div>
<!--MODAL PARA PRECIOS-->
</div>
{% endblock contenido %}
{%block script%}
$( document ).ready(function() {
  $("#abrirmodal2").focus();
});

$('#texto').change(function(){
  a = $("#texto").val().length;
  if(a>1){
    $("#tabla tbody tr").remove();
    texto = $("#texto").val();
    $.ajax({
      data: {'term':texto},
      url: "/modelos/buscar-ajax",
      type: "get",
      success: function(data){
        for(var i = 0; i<data.length; i++){
          nombre = data[i].nombre.replace(/\s+/g, '-');
          marca = data[i].marca.replace(/\s+/g, '-');
          nombrecompleto = marca + '-' + nombre;
          if(data.length==1){
            seleccionar(data[i].pk, nombrecompleto);
          }
          nuevafila = "<tr>";
          nuevafila +="<td>" + data[i].nombre + "</td>" +
                      "<td>" + data[i].marca + "</td>" +
                      "<td><a href=javascript:seleccionar("+ data[i].pk + ",'" + nombrecompleto + "');><i class=material-icons>thumb_up</i></a></td></tr>";
          $("#tabla").append(nuevafila);
       }
      }
    });
  }
});
$('#categoria').change(function(){
  a = $("#categoria").val().length;
  if(a>1){
    $("#tabla2 tbody tr").remove();
    texto = $("#categoria").val();
    nuevafila = "<tr>"
    $.ajax({
      data: {'term':texto},
      url: "/categorias/buscar-ajax",
      type: "get",
      success: function(data){
        for(var i = 0; i<data.length; i++){
          nombre = data[i].nombre.replace(/\s+/g, '-');
          if(data.length==1){
            seleccionar2(data[i].pk, nombre);
          }
          nuevafila +="<td>" + data[i].nombre + "</td>" +
                      "<td><a href=javascript:seleccionar2("+ data[i].pk + ",'" + nombre + "');><i class=material-icons>thumb_up</i></a></td></tr>";
       }
       $("#tabla2").append(nuevafila);
      }
    });
  }
});
$('#precio').change(function(){
  a = $("#precio").val().length;
  if(a>1){
    $("#tabla3 tbody tr").remove();
    texto = $("#precio").val();
    $.ajax({
      data: {'term':texto},
      url: "/precios/buscar-ajax",
      type: "get",
      success: function(data){
        for(var i = 0; i<data.length; i++){
          nuevafila = "<tr>";
          nombre = "Mayor:S/." + data[i].mayor + "--Punto:S/." + data[i].punto + "--Cliente:S/." + data[i].cliente ;
          if(data.length==1){
            seleccionar3(data[i].pk, nombre);
          }
          nuevafila +="<td>" + data[i].categoria + "</td>" +
                      "<td>" + data[i].modelo + "</td>" +
                      "<td>" + data[i].modelo + "</td>" +
                      "<td>" + data[i].mayor + "</td>" +
                      "<td>" + data[i].punto + "</td>" +
                      "<td>" + data[i].cliente + "</td>" +
                      "<td><a href=javascript:seleccionar3("+ data[i].pk + ",'" + nombre + "');><i class=material-icons>thumb_up</i></a></td></tr>";
          $("#tabla3").append(nuevafila);
       }
      }
    });
  }
});
function seleccionar(id, modelo){
  $("#id_modelo").val(id);
  $("#id_nombre").val(modelo);
  $("#exampleModal1").foundation('close');
  $("#texto").val();
  $("#abrirmodal3").focus();
}
function seleccionar2(id, categoria){
  $("#id_categoria").val(id);
  $("#id_nombrecategoria").val(categoria);
  $("#exampleModal2").foundation('close');
  $("#categoria").val();
  $("#abrirmodal").focus();
}
function seleccionar3(id, precio){
  $("#id_precio").val(id);
  $("#id_precios").val(precio);
  $("#exampleModal3").foundation('close');
  $("#precio").val();
  $("#id_stock_minimo").focus();
}
{% endblock %}

templates/productos/productos/eliminar.html
{% extends 'inicio/base.html' %}
{% block contenido %}
<div class="off-canvas-content" data-off-canvas-content>
 <div class="row titulo large-8 large-offset-2 medium-8 medium-offset-2 small-12">
   <form class="" action="#" method="post">{% csrf_token %}
      <h3>Eliminar Producto:</h3>
      <h4>¿Desea Eliminar?</h4>
      <h5 class="alerta">Nombre de Categoria: {{c.categoria.nombre|upper}}</h5>
      <h5 class="alerta">Nombre de Modelo: {{c.modelo.marca.nombre|upper}}-{{c.modelo.nombre|upper}}</h5>
      <h5 class="alerta">Precio a Mayorista: {{c.precio.mayor|upper}}</h5>
      <h5 class="alerta">Precio a Punto: {{c.precio.punto|upper}}</h5>
      <h5 class="alerta">Precio a cliente: {{c.precio.cliente|upper}}</h5>
      <h5 class="alerta">Stock Minimo: {{c.stock_minimo|upper}}</h5>
      <h5 class="alerta">Descripcion: {{c.descripcion|upper}}</h5>
      <button type="submit" class="button boton1" name="eliminar">Eliminar</button>
    </form>
  </div>
</div>
{% endblock %}